CREATE TABLE BRANCH

(
BRANCH_NAME VARCHAR2(10),
BRANCH_CITY VARCHAR2(20),
ASSETS NUMBER(10,2),
PRIMARY KEY(BRANCH_NAME)
);
CREATE TABLE ACCOUNT
(  
ACCOUNT_NO NUMBER(10,2),
BRANCH_NAME VARCHAR2(10),
BALANCE NUMBER(10,2),
PRIMARY KEY(ACCOUNT_NO),
FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME) 
);

CREATE TABLE DEPOSITOR
(
CUSTOMER_NAME VARCHAR2(20),
ACCOUNT_NO NUMBER(10,2),
PRIMARY KEY(CUSTOMER_NAME),
FOREIGN KEY(ACCOUNT_NO) REFERENCES account(account_no)
);
CREATE TABLE CUSTOMER
(
CUSTOMER_NAME VARCHAR2(10),
CUSTOMER_STREET VARCHAR2(20),
CITY VARCHAR2(10),
PRIMARY KEY(CUSTOMER_STREET),
FOREIGN KEY(CUSTOMER_NAME) references depositor(customer_name)
);
CREATE TABLE LOAN
(
LOAN_NUMBER NUMBER(10,2),
BRANCH_NAME VARCHAR2(10),
AMOUNT NUMBER(10,2),
PRIMARY KEY(LOAN_NUMBER),
FOREIGN KEY(BRANCH_NAME) references branch(branch_name)
);
CREATE TABLE BORROWER
(
CUSTOMER_NAME VARCHAR2(10),
LOAN_NUMBER number(10,2),
FOREIGN KEY(CUSTOMER_NAME) references depositor(customer_name),
FOREIGN KEY(LOAN_NUMBER) references loan(loan_number)
);
INSERT INTO branch values
('bms','blore',20000);
SELECT * FROM branch;

INSERT INTO account values
(10,'bms',1000);
SELECT * FROM account;

INSERT INTO depositor values
('rahul',10);
SELECT * FROM depositor;

INSERT INTO customer values
('rahul','bull road','blore');
SELECT * FROM customer;

INSERT INTO loan values
(11,'bms',5000);
SELECT * FROM loan;

INSERT INTO borrower values
('rahul',11);
SELECT * FROM borrower;
